### ISSUE TITLE
Typos in the annotation files?

### ISSUE THREAD

**Issue by xiulinyang** [biaoyanf/RecipeRef#3]
Hi I found some typos in the .ann files such as 66089, 141037, 83601 in which some spans are not complete. Could you please have a look?

**Comment by biaoyanf** [comment]
hi @xiulinyang 

This could be due to the annotation error from the annotators. Also, we obtained the source recipe from [recipedb](https://cosylab.iiitd.edu.in/recipedb/) and found that some sentences are not processed thoroughly.  But we keep it the same.   

And keep in mind that the annotation is not perfect. Post-processing might help with the model, etc but we intend to keep the data the way it is.

**Comment by xiulinyang** [comment]
> hi @xiulinyang
> 
> This could be due to the annotation error from the annotators. Also, we obtained the source recipe from [recipedb](https://cosylab.iiitd.edu.in/recipedb/) and found that some sentences are not processed thoroughly. But we keep it the same.
> 
> And keep in mind that the annotation is not perfect. Post-processing might help with the model, etc but we intend to keep the data the way it is.

Thanks for the information. :) I will close this issue.
